[server]
enableStaticServing = true
maxUploadSize = 50

[client]
showSidebarNavigation = true

[theme]
base = "light"
primaryColor = "#6D28D9"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"
textColor = "#111827"
font = "sans serif"
